export interface CompletionItem {
  label: string;
  type: "keyword" | "builtin" | "literal" | "type" | "function";
  detail?: string;
}

const JS_ITEMS: CompletionItem[] = [
  { label: "async", type: "keyword" },
  { label: "await", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "export", type: "keyword" },
  { label: "extends", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "from", type: "keyword" },
  { label: "function", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "import", type: "keyword" },
  { label: "in", type: "keyword" },
  { label: "instanceof", type: "keyword" },
  { label: "let", type: "keyword" },
  { label: "new", type: "keyword" },
  { label: "of", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "typeof", type: "keyword" },
  { label: "var", type: "keyword" },
  { label: "void", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "yield", type: "keyword" },
  { label: "true", type: "literal" },
  { label: "false", type: "literal" },
  { label: "null", type: "literal" },
  { label: "undefined", type: "literal" },
  { label: "console", type: "builtin", detail: "object" },
  { label: "document", type: "builtin", detail: "object" },
  { label: "window", type: "builtin", detail: "object" },
  { label: "Array", type: "type", detail: "constructor" },
  { label: "Object", type: "type", detail: "constructor" },
  { label: "String", type: "type", detail: "constructor" },
  { label: "Number", type: "type", detail: "constructor" },
  { label: "Boolean", type: "type", detail: "constructor" },
  { label: "Promise", type: "type", detail: "constructor" },
  { label: "Map", type: "type", detail: "constructor" },
  { label: "Set", type: "type", detail: "constructor" },
  { label: "Date", type: "type", detail: "constructor" },
  { label: "Error", type: "type", detail: "constructor" },
  { label: "Math", type: "builtin", detail: "object" },
  { label: "JSON", type: "builtin", detail: "object" },
];

const TS_ITEMS: CompletionItem[] = [
  ...JS_ITEMS,
  { label: "interface", type: "keyword" },
  { label: "type", type: "keyword" },
  { label: "enum", type: "keyword" },
  { label: "implements", type: "keyword" },
  { label: "declare", type: "keyword" },
  { label: "namespace", type: "keyword" },
  { label: "abstract", type: "keyword" },
  { label: "as", type: "keyword" },
  { label: "is", type: "keyword" },
  { label: "keyof", type: "keyword" },
  { label: "infer", type: "keyword" },
  { label: "readonly", type: "keyword" },
  { label: "unique", type: "keyword" },
  { label: "never", type: "literal" },
  { label: "unknown", type: "type" },
  { label: "any", type: "type" },
  { label: "Record", type: "type", detail: "utility" },
  { label: "Partial", type: "type", detail: "utility" },
  { label: "Required", type: "type", detail: "utility" },
  { label: "Pick", type: "type", detail: "utility" },
  { label: "Omit", type: "type", detail: "utility" },
  { label: "Exclude", type: "type", detail: "utility" },
  { label: "Extract", type: "type", detail: "utility" },
  { label: "ReturnType", type: "type", detail: "utility" },
];

const PY_ITEMS: CompletionItem[] = [
  { label: "and", type: "keyword" },
  { label: "as", type: "keyword" },
  { label: "assert", type: "keyword" },
  { label: "async", type: "keyword" },
  { label: "await", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "def", type: "keyword" },
  { label: "del", type: "keyword" },
  { label: "elif", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "except", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "from", type: "keyword" },
  { label: "global", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "import", type: "keyword" },
  { label: "in", type: "keyword" },
  { label: "is", type: "keyword" },
  { label: "lambda", type: "keyword" },
  { label: "nonlocal", type: "keyword" },
  { label: "not", type: "keyword" },
  { label: "or", type: "keyword" },
  { label: "pass", type: "keyword" },
  { label: "raise", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "with", type: "keyword" },
  { label: "yield", type: "keyword" },
  { label: "True", type: "literal" },
  { label: "False", type: "literal" },
  { label: "None", type: "literal" },
  { label: "self", type: "builtin" },
  { label: "print", type: "function" },
  { label: "range", type: "function" },
  { label: "len", type: "function" },
  { label: "int", type: "type" },
  { label: "str", type: "type" },
  { label: "float", type: "type" },
  { label: "list", type: "type" },
  { label: "dict", type: "type" },
  { label: "tuple", type: "type" },
  { label: "set", type: "type" },
  { label: "bool", type: "type" },
  { label: "bytes", type: "type" },
  { label: "super", type: "function" },
  { label: "isinstance", type: "function" },
  { label: "enumerate", type: "function" },
  { label: "zip", type: "function" },
  { label: "map", type: "function" },
  { label: "filter", type: "function" },
  { label: "sorted", type: "function" },
];

const GO_ITEMS: CompletionItem[] = [
  { label: "break", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "chan", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "defer", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "fallthrough", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "func", type: "keyword" },
  { label: "go", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "import", type: "keyword" },
  { label: "interface", type: "keyword" },
  { label: "map", type: "keyword" },
  { label: "package", type: "keyword" },
  { label: "range", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "select", type: "keyword" },
  { label: "struct", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "type", type: "keyword" },
  { label: "var", type: "keyword" },
  { label: "true", type: "literal" },
  { label: "false", type: "literal" },
  { label: "nil", type: "literal" },
  { label: "iota", type: "literal" },
  { label: "append", type: "function", detail: "builtin" },
  { label: "cap", type: "function", detail: "builtin" },
  { label: "close", type: "function", detail: "builtin" },
  { label: "copy", type: "function", detail: "builtin" },
  { label: "delete", type: "function", detail: "builtin" },
  { label: "len", type: "function", detail: "builtin" },
  { label: "make", type: "function", detail: "builtin" },
  { label: "new", type: "function", detail: "builtin" },
  { label: "panic", type: "function", detail: "builtin" },
  { label: "println", type: "function", detail: "builtin" },
  { label: "recover", type: "function", detail: "builtin" },
  { label: "fmt", type: "builtin", detail: "package" },
  { label: "strings", type: "builtin", detail: "package" },
  { label: "strconv", type: "builtin", detail: "package" },
  { label: "os", type: "builtin", detail: "package" },
  { label: "io", type: "builtin", detail: "package" },
  { label: "errors", type: "builtin", detail: "package" },
  { label: "context", type: "builtin", detail: "package" },
];

const RUST_ITEMS: CompletionItem[] = [
  { label: "as", type: "keyword" },
  { label: "async", type: "keyword" },
  { label: "await", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "const", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "crate", type: "keyword" },
  { label: "dyn", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "enum", type: "keyword" },
  { label: "extern", type: "keyword" },
  { label: "fn", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "impl", type: "keyword" },
  { label: "in", type: "keyword" },
  { label: "let", type: "keyword" },
  { label: "loop", type: "keyword" },
  { label: "match", type: "keyword" },
  { label: "mod", type: "keyword" },
  { label: "move", type: "keyword" },
  { label: "mut", type: "keyword" },
  { label: "pub", type: "keyword" },
  { label: "ref", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "self", type: "keyword" },
  { label: "Self", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "struct", type: "keyword" },
  { label: "super", type: "keyword" },
  { label: "trait", type: "keyword" },
  { label: "type", type: "keyword" },
  { label: "unsafe", type: "keyword" },
  { label: "use", type: "keyword" },
  { label: "where", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "true", type: "literal" },
  { label: "false", type: "literal" },
  { label: "Some", type: "literal" },
  { label: "None", type: "literal" },
  { label: "Ok", type: "literal" },
  { label: "Err", type: "literal" },
  { label: "Vec", type: "type" },
  { label: "String", type: "type" },
  { label: "Box", type: "type" },
  { label: "Rc", type: "type" },
  { label: "Arc", type: "type" },
  { label: "Option", type: "type" },
  { label: "Result", type: "type" },
  { label: "println", type: "function", detail: "macro" },
  { label: "format", type: "function", detail: "macro" },
  { label: "vec", type: "function", detail: "macro" },
  { label: "panic", type: "function", detail: "macro" },
  { label: "assert", type: "function", detail: "macro" },
  { label: "todo", type: "function", detail: "macro" },
  { label: "unimplemented", type: "function", detail: "macro" },
];

const JAVA_ITEMS: CompletionItem[] = [
  { label: "abstract", type: "keyword" },
  { label: "boolean", type: "keyword" },
  { label: "break", type: "keyword" },
  { label: "byte", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "catch", type: "keyword" },
  { label: "char", type: "keyword" },
  { label: "class", type: "keyword" },
  { label: "continue", type: "keyword" },
  { label: "default", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "double", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "extends", type: "keyword" },
  { label: "final", type: "keyword" },
  { label: "finally", type: "keyword" },
  { label: "float", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "if", type: "keyword" },
  { label: "implements", type: "keyword" },
  { label: "import", type: "keyword" },
  { label: "instanceof", type: "keyword" },
  { label: "int", type: "keyword" },
  { label: "interface", type: "keyword" },
  { label: "long", type: "keyword" },
  { label: "new", type: "keyword" },
  { label: "package", type: "keyword" },
  { label: "private", type: "keyword" },
  { label: "protected", type: "keyword" },
  { label: "public", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "short", type: "keyword" },
  { label: "static", type: "keyword" },
  { label: "super", type: "keyword" },
  { label: "switch", type: "keyword" },
  { label: "this", type: "keyword" },
  { label: "throw", type: "keyword" },
  { label: "throws", type: "keyword" },
  { label: "try", type: "keyword" },
  { label: "void", type: "keyword" },
  { label: "volatile", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "true", type: "literal" },
  { label: "false", type: "literal" },
  { label: "null", type: "literal" },
  { label: "String", type: "type" },
  { label: "Integer", type: "type" },
  { label: "Double", type: "type" },
  { label: "Boolean", type: "type" },
  { label: "List", type: "type" },
  { label: "Map", type: "type" },
  { label: "Set", type: "type" },
  { label: "ArrayList", type: "type" },
  { label: "HashMap", type: "type" },
  { label: "System", type: "builtin" },
];

const SQL_ITEMS: CompletionItem[] = [
  { label: "SELECT", type: "keyword" },
  { label: "FROM", type: "keyword" },
  { label: "WHERE", type: "keyword" },
  { label: "INSERT", type: "keyword" },
  { label: "INTO", type: "keyword" },
  { label: "VALUES", type: "keyword" },
  { label: "UPDATE", type: "keyword" },
  { label: "SET", type: "keyword" },
  { label: "DELETE", type: "keyword" },
  { label: "CREATE", type: "keyword" },
  { label: "TABLE", type: "keyword" },
  { label: "ALTER", type: "keyword" },
  { label: "DROP", type: "keyword" },
  { label: "INDEX", type: "keyword" },
  { label: "JOIN", type: "keyword" },
  { label: "INNER", type: "keyword" },
  { label: "LEFT", type: "keyword" },
  { label: "RIGHT", type: "keyword" },
  { label: "OUTER", type: "keyword" },
  { label: "ON", type: "keyword" },
  { label: "AND", type: "keyword" },
  { label: "OR", type: "keyword" },
  { label: "NOT", type: "keyword" },
  { label: "NULL", type: "literal" },
  { label: "IS", type: "keyword" },
  { label: "IN", type: "keyword" },
  { label: "BETWEEN", type: "keyword" },
  { label: "LIKE", type: "keyword" },
  { label: "ORDER", type: "keyword" },
  { label: "BY", type: "keyword" },
  { label: "GROUP", type: "keyword" },
  { label: "HAVING", type: "keyword" },
  { label: "LIMIT", type: "keyword" },
  { label: "OFFSET", type: "keyword" },
  { label: "AS", type: "keyword" },
  { label: "DISTINCT", type: "keyword" },
  { label: "CASE", type: "keyword" },
  { label: "WHEN", type: "keyword" },
  { label: "THEN", type: "keyword" },
  { label: "ELSE", type: "keyword" },
  { label: "END", type: "keyword" },
  { label: "EXISTS", type: "keyword" },
  { label: "UNION", type: "keyword" },
  { label: "ALL", type: "keyword" },
  { label: "TRUE", type: "literal" },
  { label: "FALSE", type: "literal" },
  { label: "COUNT", type: "function" },
  { label: "SUM", type: "function" },
  { label: "AVG", type: "function" },
  { label: "MIN", type: "function" },
  { label: "MAX", type: "function" },
  { label: "COALESCE", type: "function" },
];

const CSS_ITEMS: CompletionItem[] = [
  { label: "align-content", type: "keyword" },
  { label: "align-items", type: "keyword" },
  { label: "align-self", type: "keyword" },
  { label: "animation", type: "keyword" },
  { label: "background", type: "keyword" },
  { label: "border", type: "keyword" },
  { label: "border-radius", type: "keyword" },
  { label: "bottom", type: "keyword" },
  { label: "box-shadow", type: "keyword" },
  { label: "box-sizing", type: "keyword" },
  { label: "color", type: "keyword" },
  { label: "display", type: "keyword" },
  { label: "flex", type: "keyword" },
  { label: "flex-direction", type: "keyword" },
  { label: "flex-wrap", type: "keyword" },
  { label: "font-size", type: "keyword" },
  { label: "font-weight", type: "keyword" },
  { label: "gap", type: "keyword" },
  { label: "grid", type: "keyword" },
  { label: "grid-column", type: "keyword" },
  { label: "grid-row", type: "keyword" },
  { label: "grid-template-columns", type: "keyword" },
  { label: "height", type: "keyword" },
  { label: "justify-content", type: "keyword" },
  { label: "left", type: "keyword" },
  { label: "line-height", type: "keyword" },
  { label: "margin", type: "keyword" },
  { label: "max-height", type: "keyword" },
  { label: "max-width", type: "keyword" },
  { label: "min-height", type: "keyword" },
  { label: "min-width", type: "keyword" },
  { label: "opacity", type: "keyword" },
  { label: "overflow", type: "keyword" },
  { label: "padding", type: "keyword" },
  { label: "position", type: "keyword" },
  { label: "right", type: "keyword" },
  { label: "text-align", type: "keyword" },
  { label: "text-decoration", type: "keyword" },
  { label: "top", type: "keyword" },
  { label: "transform", type: "keyword" },
  { label: "transition", type: "keyword" },
  { label: "width", type: "keyword" },
  { label: "z-index", type: "keyword" },
  { label: "@media", type: "keyword" },
  { label: "@keyframes", type: "keyword" },
  { label: "@import", type: "keyword" },
  { label: "@font-face", type: "keyword" },
  { label: "auto", type: "literal" },
  { label: "inherit", type: "literal" },
  { label: "initial", type: "literal" },
  { label: "none", type: "literal" },
  { label: "transparent", type: "literal" },
  { label: "center", type: "literal" },
  { label: "relative", type: "literal" },
  { label: "absolute", type: "literal" },
  { label: "fixed", type: "literal" },
  { label: "sticky", type: "literal" },
  { label: "flex", type: "literal" },
  { label: "grid", type: "literal" },
  { label: "block", type: "literal" },
  { label: "inline", type: "literal" },
  { label: "hidden", type: "literal" },
];

const BASH_ITEMS: CompletionItem[] = [
  { label: "if", type: "keyword" },
  { label: "then", type: "keyword" },
  { label: "else", type: "keyword" },
  { label: "elif", type: "keyword" },
  { label: "fi", type: "keyword" },
  { label: "for", type: "keyword" },
  { label: "while", type: "keyword" },
  { label: "do", type: "keyword" },
  { label: "done", type: "keyword" },
  { label: "case", type: "keyword" },
  { label: "esac", type: "keyword" },
  { label: "in", type: "keyword" },
  { label: "function", type: "keyword" },
  { label: "select", type: "keyword" },
  { label: "until", type: "keyword" },
  { label: "time", type: "keyword" },
  { label: "return", type: "keyword" },
  { label: "exit", type: "keyword" },
  { label: "export", type: "keyword" },
  { label: "local", type: "keyword" },
  { label: "declare", type: "keyword" },
  { label: "readonly", type: "keyword" },
  { label: "set", type: "keyword" },
  { label: "unset", type: "keyword" },
  { label: "shift", type: "keyword" },
  { label: "source", type: "keyword" },
  { label: "true", type: "literal" },
  { label: "false", type: "literal" },
  { label: "echo", type: "function" },
  { label: "printf", type: "function" },
  { label: "read", type: "function" },
  { label: "cat", type: "function" },
  { label: "grep", type: "function" },
  { label: "sed", type: "function" },
  { label: "awk", type: "function" },
  { label: "find", type: "function" },
  { label: "sort", type: "function" },
  { label: "uniq", type: "function" },
  { label: "wc", type: "function" },
  { label: "head", type: "function" },
  { label: "tail", type: "function" },
  { label: "cut", type: "function" },
  { label: "tr", type: "function" },
  { label: "xargs", type: "function" },
  { label: "mkdir", type: "function" },
  { label: "rm", type: "function" },
  { label: "cp", type: "function" },
  { label: "mv", type: "function" },
  { label: "ls", type: "function" },
  { label: "chmod", type: "function" },
  { label: "chown", type: "function" },
  { label: "cd", type: "function" },
  { label: "pwd", type: "function" },
  { label: "test", type: "function" },
];

const SMALL_LANG_ITEMS: Record<string, CompletionItem[]> = {
  JSON: [
    { label: "true", type: "literal" },
    { label: "false", type: "literal" },
    { label: "null", type: "literal" },
  ],
  HTML: [
    { label: "<div>", type: "keyword" }, { label: "</div>", type: "keyword" },
    { label: "<span>", type: "keyword" }, { label: "</span>", type: "keyword" },
    { label: "<p>", type: "keyword" }, { label: "</p>", type: "keyword" },
    { label: "<a>", type: "keyword" }, { label: "</a>", type: "keyword" },
    { label: "<img>", type: "keyword" },
    { label: "<h1>", type: "keyword" }, { label: "</h1>", type: "keyword" },
    { label: "<h2>", type: "keyword" }, { label: "</h2>", type: "keyword" },
    { label: "<h3>", type: "keyword" }, { label: "</h3>", type: "keyword" },
    { label: "<ul>", type: "keyword" }, { label: "</ul>", type: "keyword" },
    { label: "<li>", type: "keyword" }, { label: "</li>", type: "keyword" },
    { label: "<table>", type: "keyword" }, { label: "</table>", type: "keyword" },
    { label: "<form>", type: "keyword" }, { label: "</form>", type: "keyword" },
    { label: "<input>", type: "keyword" },
    { label: "<button>", type: "keyword" }, { label: "</button>", type: "keyword" },
    { label: "<script>", type: "keyword" }, { label: "</script>", type: "keyword" },
    { label: "<style>", type: "keyword" }, { label: "</style>", type: "keyword" },
    { label: "<link>", type: "keyword" },
    { label: "<meta>", type: "keyword" },
    { label: "class=", type: "keyword" },
    { label: "id=", type: "keyword" },
    { label: "href=", type: "keyword" },
    { label: "src=", type: "keyword" },
    { label: "style=", type: "keyword" },
  ],
  YAML: [
    { label: "true", type: "literal" },
    { label: "false", type: "literal" },
    { label: "null", type: "literal" },
    { label: "yes", type: "literal" },
    { label: "no", type: "literal" },
  ],
  XML: [
    { label: "<?xml", type: "keyword" },
    { label: "<!--", type: "keyword" },
    { label: "-->", type: "keyword" },
    { label: "xmlns", type: "keyword" },
    { label: "encoding", type: "keyword" },
    { label: "version", type: "keyword" },
  ],
  C: [
    { label: "auto", type: "keyword" }, { label: "break", type: "keyword" },
    { label: "case", type: "keyword" }, { label: "char", type: "keyword" },
    { label: "const", type: "keyword" }, { label: "continue", type: "keyword" },
    { label: "default", type: "keyword" }, { label: "do", type: "keyword" },
    { label: "double", type: "keyword" }, { label: "else", type: "keyword" },
    { label: "enum", type: "keyword" }, { label: "extern", type: "keyword" },
    { label: "float", type: "keyword" }, { label: "for", type: "keyword" },
    { label: "goto", type: "keyword" }, { label: "if", type: "keyword" },
    { label: "int", type: "keyword" }, { label: "long", type: "keyword" },
    { label: "register", type: "keyword" }, { label: "return", type: "keyword" },
    { label: "short", type: "keyword" }, { label: "signed", type: "keyword" },
    { label: "sizeof", type: "keyword" }, { label: "static", type: "keyword" },
    { label: "struct", type: "keyword" }, { label: "switch", type: "keyword" },
    { label: "typedef", type: "keyword" }, { label: "union", type: "keyword" },
    { label: "unsigned", type: "keyword" }, { label: "void", type: "keyword" },
    { label: "volatile", type: "keyword" }, { label: "while", type: "keyword" },
    { label: "NULL", type: "literal" },
    { label: "printf", type: "function" }, { label: "scanf", type: "function" },
    { label: "malloc", type: "function" }, { label: "free", type: "function" },
    { label: "strlen", type: "function" }, { label: "strcpy", type: "function" },
  ],
  Ruby: [
    { label: "begin", type: "keyword" }, { label: "break", type: "keyword" },
    { label: "case", type: "keyword" }, { label: "class", type: "keyword" },
    { label: "def", type: "keyword" }, { label: "do", type: "keyword" },
    { label: "else", type: "keyword" }, { label: "elsif", type: "keyword" },
    { label: "end", type: "keyword" }, { label: "ensure", type: "keyword" },
    { label: "for", type: "keyword" }, { label: "if", type: "keyword" },
    { label: "in", type: "keyword" }, { label: "module", type: "keyword" },
    { label: "next", type: "keyword" }, { label: "raise", type: "keyword" },
    { label: "redo", type: "keyword" }, { label: "rescue", type: "keyword" },
    { label: "retry", type: "keyword" }, { label: "return", type: "keyword" },
    { label: "self", type: "keyword" }, { label: "super", type: "keyword" },
    { label: "then", type: "keyword" }, { label: "undef", type: "keyword" },
    { label: "unless", type: "keyword" }, { label: "until", type: "keyword" },
    { label: "while", type: "keyword" }, { label: "yield", type: "keyword" },
    { label: "true", type: "literal" }, { label: "false", type: "literal" },
    { label: "nil", type: "literal" },
    { label: "puts", type: "function" }, { label: "print", type: "function" },
    { label: "gets", type: "function" }, { label: "chomp", type: "function" },
    { label: "require", type: "keyword" }, { label: "include", type: "keyword" },
    { label: "attr_accessor", type: "keyword" },
    { label: "attr_reader", type: "keyword" },
  ],
  PHP: [
    { label: "abstract", type: "keyword" }, { label: "and", type: "keyword" },
    { label: "array", type: "keyword" }, { label: "as", type: "keyword" },
    { label: "break", type: "keyword" }, { label: "case", type: "keyword" },
    { label: "catch", type: "keyword" }, { label: "class", type: "keyword" },
    { label: "const", type: "keyword" }, { label: "continue", type: "keyword" },
    { label: "default", type: "keyword" }, { label: "do", type: "keyword" },
    { label: "echo", type: "keyword" }, { label: "else", type: "keyword" },
    { label: "elseif", type: "keyword" }, { label: "extends", type: "keyword" },
    { label: "final", type: "keyword" }, { label: "for", type: "keyword" },
    { label: "foreach", type: "keyword" }, { label: "function", type: "keyword" },
    { label: "if", type: "keyword" }, { label: "implements", type: "keyword" },
    { label: "include", type: "keyword" }, { label: "interface", type: "keyword" },
    { label: "namespace", type: "keyword" }, { label: "new", type: "keyword" },
    { label: "or", type: "keyword" }, { label: "private", type: "keyword" },
    { label: "protected", type: "keyword" }, { label: "public", type: "keyword" },
    { label: "return", type: "keyword" }, { label: "static", type: "keyword" },
    { label: "switch", type: "keyword" }, { label: "throw", type: "keyword" },
    { label: "try", type: "keyword" }, { label: "use", type: "keyword" },
    { label: "var", type: "keyword" }, { label: "while", type: "keyword" },
    { label: "true", type: "literal" }, { label: "false", type: "literal" },
    { label: "null", type: "literal" },
  ],
  Swift: [
    { label: "associatedtype", type: "keyword" }, { label: "break", type: "keyword" },
    { label: "case", type: "keyword" }, { label: "catch", type: "keyword" },
    { label: "class", type: "keyword" }, { label: "continue", type: "keyword" },
    { label: "default", type: "keyword" }, { label: "defer", type: "keyword" },
    { label: "do", type: "keyword" }, { label: "else", type: "keyword" },
    { label: "enum", type: "keyword" }, { label: "extension", type: "keyword" },
    { label: "fallthrough", type: "keyword" }, { label: "for", type: "keyword" },
    { label: "func", type: "keyword" }, { label: "guard", type: "keyword" },
    { label: "if", type: "keyword" }, { label: "in", type: "keyword" },
    { label: "init", type: "keyword" }, { label: "inout", type: "keyword" },
    { label: "let", type: "keyword" }, { label: "mutating", type: "keyword" },
    { label: "nil", type: "literal" }, { label: "private", type: "keyword" },
    { label: "protocol", type: "keyword" }, { label: "public", type: "keyword" },
    { label: "repeat", type: "keyword" }, { label: "return", type: "keyword" },
    { label: "self", type: "keyword" }, { label: "static", type: "keyword" },
    { label: "struct", type: "keyword" }, { label: "subscript", type: "keyword" },
    { label: "switch", type: "keyword" }, { label: "throw", type: "keyword" },
    { label: "try", type: "keyword" }, { label: "typealias", type: "keyword" },
    { label: "var", type: "keyword" }, { label: "where", type: "keyword" },
    { label: "while", type: "keyword" }, { label: "true", type: "literal" },
    { label: "false", type: "literal" },
    { label: "Array", type: "type" }, { label: "Dictionary", type: "type" },
    { label: "Set", type: "type" }, { label: "String", type: "type" },
    { label: "Int", type: "type" }, { label: "Double", type: "type" },
    { label: "Float", type: "type" }, { label: "Bool", type: "type" },
    { label: "Optional", type: "type" }, { label: "Result", type: "type" },
    { label: "print", type: "function" },
  ],
  Kotlin: [
    { label: "as", type: "keyword" }, { label: "break", type: "keyword" },
    { label: "class", type: "keyword" }, { label: "continue", type: "keyword" },
    { label: "do", type: "keyword" }, { label: "else", type: "keyword" },
    { label: "false", type: "literal" }, { label: "for", type: "keyword" },
    { label: "fun", type: "keyword" }, { label: "if", type: "keyword" },
    { label: "in", type: "keyword" }, { label: "interface", type: "keyword" },
    { label: "is", type: "keyword" }, { label: "null", type: "literal" },
    { label: "object", type: "keyword" }, { label: "package", type: "keyword" },
    { label: "return", type: "keyword" }, { label: "super", type: "keyword" },
    { label: "this", type: "keyword" }, { label: "throw", type: "keyword" },
    { label: "true", type: "literal" }, { label: "try", type: "keyword" },
    { label: "typealias", type: "keyword" }, { label: "val", type: "keyword" },
    { label: "var", type: "keyword" }, { label: "when", type: "keyword" },
    { label: "while", type: "keyword" },
    { label: "List", type: "type" }, { label: "Map", type: "type" },
    { label: "Set", type: "type" }, { label: "String", type: "type" },
    { label: "Int", type: "type" }, { label: "Double", type: "type" },
    { label: "Float", type: "type" }, { label: "Boolean", type: "type" },
    { label: "Unit", type: "type" }, { label: "Array", type: "type" },
    { label: "println", type: "function" },
    { label: "suspend", type: "keyword" },
    { label: "data", type: "keyword" },
    { label: "sealed", type: "keyword" },
    { label: "inline", type: "keyword" },
    { label: "inner", type: "keyword" },
    { label: "companion", type: "keyword" },
    { label: "init", type: "keyword" },
    { label: "lateinit", type: "keyword" },
    { label: "override", type: "keyword" },
    { label: "abstract", type: "keyword" },
    { label: "open", type: "keyword" },
    { label: "private", type: "keyword" },
    { label: "protected", type: "keyword" },
    { label: "internal", type: "keyword" },
    { label: "public", type: "keyword" },
  ],
};

const COMPLETIONS: Record<string, CompletionItem[]> = {
  JavaScript: JS_ITEMS,
  TypeScript: TS_ITEMS,
  Python: PY_ITEMS,
  Go: GO_ITEMS,
  Rust: RUST_ITEMS,
  Java: JAVA_ITEMS,
  "C++": [...SMALL_LANG_ITEMS.C, { label: "class", type: "keyword" }, { label: "namespace", type: "keyword" }, { label: "template", type: "keyword" }, { label: "virtual", type: "keyword" }, { label: "override", type: "keyword" }, { label: "public", type: "keyword" }, { label: "private", type: "keyword" }, { label: "protected", type: "keyword" }, { label: "new", type: "keyword" }, { label: "delete", type: "keyword" }, { label: "try", type: "keyword" }, { label: "catch", type: "keyword" }, {label: "throw",type: "keyword"}, {label: "nullptr",type: "literal"}, {label: "cout",type: "function"}, {label: "cin",type: "function"}, {label: "endl",type: "literal"}, {label: "std",type: "builtin"}, {label: "vector",type: "type"}, {label: "string",type: "type"}, {label: "map",type: "type"}, {label: "set",type: "type"}, {label: "auto",type: "keyword"}, {label: "const",type: "keyword"}, {label: "static",type: "keyword"}, {label: "inline",type: "keyword"}, {label: "explicit",type: "keyword"}, {label: "mutable",type: "keyword"}, {label: "noexcept",type: "keyword"}],
  C: SMALL_LANG_ITEMS.C,
  Ruby: SMALL_LANG_ITEMS.Ruby,
  PHP: SMALL_LANG_ITEMS.PHP,
  Swift: SMALL_LANG_ITEMS.Swift,
  Kotlin: SMALL_LANG_ITEMS.Kotlin,
  SQL: SQL_ITEMS,
  JSON: SMALL_LANG_ITEMS.JSON,
  HTML: SMALL_LANG_ITEMS.HTML,
  CSS: CSS_ITEMS,
  Bash: BASH_ITEMS,
  YAML: SMALL_LANG_ITEMS.YAML,
  XML: SMALL_LANG_ITEMS.XML,
};

const TYPE_COLORS: Record<CompletionItem["type"], string> = {
  keyword: "#c586c0",
  builtin: "#4ec9b0",
  literal: "#4fc1ff",
  type: "#4ec9b0",
  function: "#dcdcaa",
};

const TYPE_ICONS: Record<CompletionItem["type"], string> = {
  keyword: "K",
  builtin: "B",
  literal: "L",
  type: "T",
  function: "F",
};

export type { CompletionItem };
export { COMPLETIONS, TYPE_COLORS, TYPE_ICONS };

export function getCompletions(
  language: string | null,
  text: string,
  cursorPos: number
): CompletionItem[] {
  if (!language || language === "Plain Text") return [];

  const items = COMPLETIONS[language];
  if (!items) return [];

  const beforeCursor = text.slice(0, cursorPos);
  const match = beforeCursor.match(/[a-zA-Z_][a-zA-Z0-9_]*$/);
  if (!match) return [];

  const prefix = match[0].toLowerCase();
  if (prefix.length < 1) return [];

  const filtered = items.filter((item) =>
    item.label.toLowerCase().startsWith(prefix)
  );

  if (filtered.length === 1 && filtered[0].label.toLowerCase() === prefix) {
    return [];
  }

  return filtered.slice(0, 12);
}

export function applyCompletion(
  text: string,
  cursorPos: number,
  item: CompletionItem
): { text: string; cursorPos: number } {
  const beforeCursor = text.slice(0, cursorPos);
  const match = beforeCursor.match(/[a-zA-Z_][a-zA-Z0-9_]*$/);
  if (!match) return { text, cursorPos };

  const start = cursorPos - match[0].length;
  const newText = text.slice(0, start) + item.label + text.slice(cursorPos);
  const newCursorPos = start + item.label.length;

  return { text: newText, cursorPos: newCursorPos };
}

export function getCursorPosition(
  text: string,
  cursorPos: number,
  lineHeight: number,
  charWidth: number,
  paddingTop: number,
  paddingLeft: number
): { top: number; left: number } {
  const lines = text.slice(0, cursorPos).split("\n");
  const line = lines.length - 1;
  const col = lines[line].length;

  return {
    top: line * lineHeight + paddingTop,
    left: col * charWidth + paddingLeft,
  };
}